"""Tests for ChatHandler."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from aiohttp import web
from aiohttp.test_utils import AioHTTPTestCase, TestClient, TestServer

from app.runtime.server.chat import ChatHandler
from app.runtime.state.session_store import SessionStore


@pytest.fixture()
def session_store(data_dir: Path) -> SessionStore:
    return SessionStore()


@pytest.fixture()
def handler(session_store: SessionStore) -> ChatHandler:
    agent = AsyncMock()
    agent.new_session = AsyncMock(return_value="session-1")
    agent.send = AsyncMock(return_value="bot reply")
    agent.list_models = AsyncMock(return_value=["gpt-4o", "gpt-4.1"])
    return ChatHandler(agent, session_store)


class TestLoadSuggestions:
    def test_no_file(self, data_dir: Path) -> None:
        result = ChatHandler._load_suggestions()
        assert result == []

    def test_with_file(self, data_dir: Path) -> None:
        from app.runtime.config.settings import cfg
        path = cfg.data_dir / "suggestions.txt"
        path.write_text("Hello\n# comment\nWorld\n\n  Spaces  \n")
        result = ChatHandler._load_suggestions()
        assert result == ["Hello", "World", "Spaces"]

    def test_empty_file(self, data_dir: Path) -> None:
        from app.runtime.config.settings import cfg
        path = cfg.data_dir / "suggestions.txt"
        path.write_text("")
        result = ChatHandler._load_suggestions()
        assert result == []


class TestListModels:
    @pytest.mark.asyncio
    async def test_returns_current_model(self, handler: ChatHandler) -> None:
        app = web.Application()
        handler.register(app.router)
        async with TestClient(TestServer(app)) as client:
            resp = await client.get("/api/chat/models")
            assert resp.status == 200
            data = await resp.json()
            assert "current" in data
            assert "models" in data
            assert data["models"] == ["gpt-4o", "gpt-4.1"]


class TestGetSuggestions:
    @pytest.mark.asyncio
    async def test_returns_list(self, handler: ChatHandler) -> None:
        app = web.Application()
        handler.register(app.router)
        async with TestClient(TestServer(app)) as client:
            resp = await client.get("/api/chat/suggestions")
            assert resp.status == 200
            data = await resp.json()
            assert isinstance(data, dict)
            assert "suggestions" in data
            assert isinstance(data["suggestions"], list)


class TestTryCommand:
    @pytest.mark.asyncio
    async def test_new_command(self, handler: ChatHandler) -> None:
        ws = AsyncMock()
        ws.send_json = AsyncMock()
        handled = await handler._try_command(ws, "/new", "")
        assert handled is True
        # CommandDispatcher sends message + done via the reply callback
        calls = [c[0][0] for c in ws.send_json.call_args_list]
        types = [c["type"] for c in calls]
        assert "message" in types
        assert "done" in types
        msg = next(c for c in calls if c["type"] == "message")
        assert "セッション" in msg["content"] or "新しい" in msg["content"]

    @pytest.mark.asyncio
    async def test_clear_command(self, handler: ChatHandler) -> None:
        ws = AsyncMock()
        ws.send_json = AsyncMock()
        handled = await handler._try_command(ws, "/clear", "")
        assert handled is True
        calls = [c[0][0] for c in ws.send_json.call_args_list]
        msg = next(c for c in calls if c["type"] == "message")
        assert "クリア" in msg["content"] or "削除" in msg["content"]

    @pytest.mark.asyncio
    async def test_not_command(self, handler: ChatHandler) -> None:
        ws = AsyncMock()
        handled = await handler._try_command(ws, "hello", "")
        assert handled is False

    @pytest.mark.asyncio
    async def test_unknown_command(self, handler: ChatHandler) -> None:
        ws = AsyncMock()
        handled = await handler._try_command(ws, "/foobar", "")
        assert handled is False


class TestDispatch:
    @pytest.mark.asyncio
    async def test_new_session(self, handler: ChatHandler) -> None:
        ws = AsyncMock()
        ws.send_json = AsyncMock()
        await handler._dispatch(ws, {"action": "new_session"})
        ws.send_json.assert_called_once()
        msg = ws.send_json.call_args[0][0]
        assert msg["type"] == "session_created"
        # Session ID is now a UUID generated by the handler
        sid = msg["session_id"]
        assert len(sid) == 36 and sid.count("-") == 4  # UUID format

    @pytest.mark.asyncio
    async def test_auto_session_on_first_message(self, handler: ChatHandler) -> None:
        """When no session is active, sending a message auto-creates one."""
        ws = AsyncMock()
        ws.send_json = AsyncMock()
        assert handler._sessions.current_session_id == ""
        await handler._send_prompt(ws, {"message": "hello"})
        # A session should now be active and the message recorded
        sid = handler._sessions.current_session_id
        assert sid
        assert len(sid) == 36  # UUID
        session = handler._sessions.get_session(sid)
        assert session is not None
        assert len(session["messages"]) == 2  # user + assistant

    @pytest.mark.asyncio
    async def test_unknown_action(self, handler: ChatHandler) -> None:
        ws = AsyncMock()
        ws.send_json = AsyncMock()
        await handler._dispatch(ws, {"action": "explode"})
        msg = ws.send_json.call_args[0][0]
        assert msg["type"] == "error"
        assert "Unknown action" in msg["content"]


class TestResumeSession:
    @pytest.mark.asyncio
    async def test_missing_session(self, handler: ChatHandler) -> None:
        ws = AsyncMock()
        ws.send_json = AsyncMock()
        await handler._resume_session(ws, "nonexistent")
        msg = ws.send_json.call_args[0][0]
        assert msg["type"] == "error"
        assert "not found" in msg["content"]

    @pytest.mark.asyncio
    async def test_existing_session(self, handler: ChatHandler) -> None:
        handler._sessions.start_session("s1")
        handler._sessions.record("user", "hello")
        ws = AsyncMock()
        ws.send_json = AsyncMock()
        await handler._resume_session(ws, "s1")
        msg = ws.send_json.call_args[0][0]
        assert msg["type"] == "session_resumed"
        assert msg["session_id"] == "s1"
